# Тема "Фреймворки Keras и PyTorch"

<h2 style="text-align: center;"><b>Самостоятельная работа</b></h2>
<h2 style="text-align: center;"><b>PyTorch. Основы: синтаксис, torch.cuda и torch.autograd</b></h2>

---

<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=500 height=400></p>

Вам необходимо ознакомиться с основами и нюансами работы фреймворка глубокого обучения PyTorch.  

Решение какой-либо задачи, будь то простая бинарная классификация или обнаружение лиц людей на видео, всегда начинается со **сбора данных**, а уже потом реализуются модели или нейронные сети и проводятся эксперименты.  

Однако разработчики быстро поняли, что писать свои нейронные сети каждый раз с нуля долго и малоэффективноо, поэтому придумали так называемые **фреймворки** - модули, в которых есть функционал, с помощью которого можно быстро и просто решать типовые задачи, и уже с помощью этих средств писать решения к более сложным задачам.

Есть много различных фреймворков глубокого обучения. Разница между ними прежде всего в том, каков общий принцип вычислений. 
Например, в **Caffe и Caffe2** вы пишете код, по сути, составляя его из готовых "кусочков", как в Lego, в **TensorFlow и Theano** вы сначала объявляете вычислительный граф, потом компилируете его и запускаете (sees.run()), в то время как в **Torch и PyTorch** вы пишете почти точно так же, как на NumPy, а граф вычислений создаётся только при запуске (то есть существует только во время выполнения, потом он "разрушается"). **Keras** позволяет как строить блоки, так и компилировать свой граф:

<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Картинка взята из этой [статьи на Хабре](https://habr.com/post/334380/)</i><p>

<h3 style="text-align: center;"><b>Установка</b></h3>

Инструкция по установке PyTorch есть на [официальном сайте PyTorch](https://pytorch.org/).

## Задание: Выполните весь код, который приведен ниже в этом файле, можете поэкспериментировать с выбором различных значений. Сохраните данный файл в виде отдельного файла Jupyter notebook, и прикрепите к данному заданию в системе (в имени файла укажите вашу фамилию и инициалы, а также номер модуля и название данной темы»).

<h3 style="text-align: center;">Синтаксис<b></b></h3>

При первом запуске необходимо установить tensorflow на основе этого фреймворка работают и Keras и Pytorch.
Для установки потребуется подключение к сети Интернет.

In [1]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.1/230.1 MB 11.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 16.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 16.4 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 397.2/397.2 kB 16.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 9.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 16.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 16.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 16.8 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 16.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440

Далее нужно установить сам PyTorch.
Для этого необходимо перейти на сайт https://pytorch.org/ и выбирая опции, сооветствующие вашему компьютеру и его конфигурации, сформировать ссылку для установки данного фреймворка.
При этом pip3 лучше заменить на !pip.

In [2]:
!pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 5.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 33.1 MB/s eta 0:00:0000:0100:01


In [3]:
!pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
# Пример старой (уже не работающей) команды.

Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.9.0+cu102 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.9.0+cu102


In [4]:
import torch # теперь можно импортировать фреймворк как обычную библиотеку

Сначала немного фактов про PyTorch:  
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision` для написания нейросетей с минимальными усилиями
- в некоторых задачах даже быстрее TensorFlow
- легко проводить вычисления на GPU


Если PyTorch представить формулой, то она будет такой:

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://ru.wikipedia.org/wiki/CUDA))

Посмотрим, как в PyTorch выполняются операции с векторами.  

Напоминание: **тензором** называется многомерный вектор, то есть:  

x = np.array([1,2,3]) - вектор = тензор размерности 1 (то есть (1,))  
y = np.array([[1, 2, 3], [4, 5, 6]]) - матрица = тензор размерности 2 (в данном случае тензор (2, 3))  
z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) - "кубик" (3, 3, 3) = тензор размерности 3 (в данном случае (3, 3, 3))

Простейшим примером 3-мерного тензора является **картинка** - это "параллелепипед" из чисел, у которого три размерности - высота, ширина и количество каналов, значит это тензор размерности 3.

Понятие тензора нужно знать потому, что в PyTorch мы оперируем переменными типа `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`), и пугаться их названий совершенно не нужно - это просто векторы, у которых несколько размерностей.

Все типы тензоров:

In [5]:
torch.HalfTensor      # 16 бит, с плавающей точкой
torch.FloatTensor     # 32 бита,  с плавающей точкой
torch.DoubleTensor    # 64 бита, с плавающей точкой

torch.ShortTensor     # 16 бит, целочисленный, знаковый
torch.IntTensor       # 32 бита, целочисленный, знаковый
torch.LongTensor      # 64 бита, целочисленный, знаковый

torch.CharTensor      # 8 бит, целочисленный, знаковый
torch.ByteTensor      # 8 бит, целочисленный, беззнаковый

torch.ByteTensor

Мы будем использовать только `torch.FloatTensor()` и `torch.IntTensor()`. 

Перейдём к делу:

* Создание тензоров:

In [6]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [7]:
a.shape

torch.Size([2])

In [8]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
b.shape

torch.Size([2, 3])

In [10]:
x = torch.FloatTensor(2,3,4)

In [11]:
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
x = torch.FloatTensor(100)
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [13]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Обратите внимание** - если вы создаете тензор через задание размерностей (как в примере выше), то он изначально заполняюстя случайным "мусором". Что бы инициализировать заполенние тензора нулями, нужно написать .zero_() в конце:

In [11]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[ 926169652,  775303738,  892549431,  576336697],
         [1701061164, 1684956528, 1768124005, 1834972005]],

        [[ 975336549, 1702195828, 1852121644, 1701734759],
         [ 908212770,  929456696,  761346105,  892954212]],

        [[ 926168109,  892939618,  925721394,  895627828],
         [ 959591522,  574109492, 1953702444, 1937077345]]], dtype=torch.int32)

In [12]:
x = torch.IntTensor(3, 2, 4).zero_()
x

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

Аналог функции `np.reshape()` == `torch.view()`:

In [13]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [14]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Обратите внимание** - torch.view() создает новый тензор, а не изменяет старый!

In [15]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [16]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

* Изменение типа тензора:

In [17]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [18]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [19]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

Обратите внимание, что при `.type_as()` создаётся новый тензор (старый не меняется), то есть это не in-place операция:

In [20]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Индексация точная такая же, как и в NumPy:

In [15]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [16]:
a[0]

tensor([100.,  20.,  35.])

In [23]:
a[0][0]

tensor(100.)

In [18]:
a[0:3, 0:1]

tensor([[100.],
        [ 15.],
        [ 52.]])

**Арифметика и булевы операции** работаю также, как и в NumPy, **НО** лучше использовать не опреаторы `+`, `-`, `*`, `/`, а их аналоги:  

| Оператор | Аналог |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Сложение:

In [25]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [26]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

Лучше:

In [27]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [28]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [29]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* Вычитание:

In [30]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

Лучше:

In [31]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

* Умножение (поэлементное):

In [32]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

Лучше:

In [33]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

* Деление (поэлементное):

In [34]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [35]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

Лучше:

In [36]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

Заметьте, все эти операции **не меняют исходные тензоры**, а **создают новые**:

In [37]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [38]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

* **Операторы сравнения**:

In [39]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [40]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [41]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [42]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [43]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

* **Булевы маски**:

In [44]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [45]:
b[a == b]

tensor([100., 200., 300.])

Опять же, тензоры не меняются:

In [46]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [47]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

Применение **стандартных функций** такое же, как и в numpy - поэлементное:

In [48]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [49]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [50]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [51]:
a.cos()

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.8391,  0.4081,  0.1543],
        [ 0.8623,  0.4872, -0.0221]])

In [52]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [53]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [54]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [55]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

**Сумма, среднее, максимум, минимум**:

In [56]:
a.sum()

tensor(666.)

In [57]:
a.mean()

tensor(74.)

По осям:

In [58]:
a.sum(0)

tensor([111., 222., 333.])

In [59]:
a.sum(1)

tensor([  6.,  60., 600.])

In [60]:
a.max()

tensor(300.)

In [61]:
a.max(0)

torch.return_types.max(
values=tensor([100., 200., 300.]),
indices=tensor([2, 2, 2]))

In [62]:
a.min()

tensor(1.)

In [63]:
a.min(0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

Обратите внимание - второй тензор при вызове функций .max() и .min() - это индексы этих максимальных/минимальных элементов по указанной размерности (то есть в данном случае a.min() вернул (1, 2, 3) - минимумы по 0 оси (по столбцам), и их индексы по 0-ой оси (0,0,0) (номер каждого элемента в своем столбце)).

**Матричные операции:**

* Транспонирование матрицы (тензора):

In [64]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [65]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

И снова - сам тензор не меняется (то есть при вызове создаётся новый):

In [66]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* Скалярное произведение векторов (1-мерных тензоров):

In [67]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [68]:
a.dot(b)

tensor(-141.)

In [69]:
a @ b

tensor(-141.)

In [70]:
type(a)

torch.Tensor

In [71]:
type(b)

torch.Tensor

In [72]:
type(a @ b)

torch.Tensor

* Матричное умножение:

In [73]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [74]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [75]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

Тензоры неизменны:

In [76]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [77]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

In [78]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [79]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [80]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

Если "развернуть" тензор b просто в массив элементов (`torch.view(-1)`), умножение будет как на столбец:

In [81]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [82]:
b.view(-1)

tensor([ -1., -10., 100.])

In [83]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [84]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

**Перевод из NumPy в PyTorch**:

In [85]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.71795506, 0.04792642, 0.71460918],
       [0.56815408, 0.02730152, 0.53909641],
       [0.94402003, 0.9158407 , 0.66311908]])

In [86]:
b = torch.from_numpy(a)
b

tensor([[0.7180, 0.0479, 0.7146],
        [0.5682, 0.0273, 0.5391],
        [0.9440, 0.9158, 0.6631]], dtype=torch.float64)

**НО!** Обратите внимание - a и b в этом случае будут использовать одно и то же хранилище данных, то есть измение одного тензора будет менять и другой:

In [87]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [88]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Перевод из PyTorch в NumPy:**

In [89]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22],
         [2.5226e-18, 1.0372e-08, 1.0243e-11, 3.0880e-09]],

        [[1.7188e-04, 4.0061e-11, 6.4825e-10, 2.9573e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]]])

In [90]:
type(a)

torch.Tensor

In [91]:
x = a.numpy()
x

array([[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
        [0.0000000e+00, 0.0000000e+00, 7.7052459e+31, 7.2147959e+22],
        [2.5225907e-18, 1.0371922e-08, 1.0242513e-11, 3.0880298e-09]],

       [[1.7187820e-04, 4.0061489e-11, 6.4824512e-10, 2.9573212e-18],
        [6.7333120e+22, 1.7590538e+22, 1.7184218e+25, 4.3221663e+27],
        [6.1971537e-04, 7.2443192e+22, 1.7728345e+28, 7.0366722e+22]]],
      dtype=float32)

In [92]:
x.shape

(2, 3, 4)

In [93]:
type(x)

numpy.ndarray

Напишем функцию `forward_pass(X, w)` ($w_0$ входит в $w$) для одного нейрона (с сигмоидой) с помощью PyTorch:

In [94]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [95]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


<h3 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

[Краткое видео про то, как GPU используется в обучении нейросетей](https://www.youtube.com/watch?v=EobhK0UZm80)


Все вычисления в PyTorch можно проводить как на CPU, так и на GPU (Graphical Processing Unit) (если она у вас есть). В PyTorch переключение между ними делается очень просто, что является одной из ключевых его особенностей.

In [14]:
torch.cuda.is_available()  # проверяем установлена ли CUDA
                           # если в результате выполнения данной команды получаем ответ False, то это означает, 
                           # что данный модуль не установлен

False

Если у вас при выполнении предыдущей команды вышел отрицательный ответ "False", то все строчки в этом разделе вы не сможете выполнить. Причиной почему модуль CUDA не установлен самые разнообразные от отсутствия соответствующей видеокарты в вашем компьютере, до конфликта версий различных модулей в PyTorch.

Для решения проблемы проще всего использовать другой сервис - [Google Colaboratory](https://colab.research.google.com), чтобы работать с GPU. Загрузите туда этот ноутбук (`Upload notebook`)
- В Colab нажмите в меню сверху: `Runtime` -> `Change Runtime Type` -> `GPU`, где изначально стоит `None`

Для того чтобы использовать данный сервис, необходимо иметь Google аккаунт.

In [97]:
torch.zeros(1).cuda()

tensor([0.], device='cuda:0')

In [98]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[0.1032, 0.4794, 0.8795,  ..., 0.7577, 0.8586, 0.3242],
        [0.6030, 0.2875, 0.3329,  ..., 0.2386, 0.0396, 0.9825],
        [0.3888, 0.0443, 0.4865,  ..., 0.9311, 0.9873, 0.8788],
        ...,
        [0.6679, 0.2623, 0.6735,  ..., 0.5274, 0.0518, 0.0285],
        [0.6415, 0.7920, 0.0130,  ..., 0.3158, 0.3530, 0.1800],
        [0.2182, 0.0010, 0.2733,  ..., 0.8556, 0.1585, 0.9253]])

In [99]:
x.is_cuda

False

Переместим на GPU:

In [100]:
x = x.cuda()

In [101]:
x.is_cuda

True

In [102]:
x

tensor([[0.1032, 0.4794, 0.8795,  ..., 0.7577, 0.8586, 0.3242],
        [0.6030, 0.2875, 0.3329,  ..., 0.2386, 0.0396, 0.9825],
        [0.3888, 0.0443, 0.4865,  ..., 0.9311, 0.9873, 0.8788],
        ...,
        [0.6679, 0.2623, 0.6735,  ..., 0.5274, 0.0518, 0.0285],
        [0.6415, 0.7920, 0.0130,  ..., 0.3158, 0.3530, 0.1800],
        [0.2182, 0.0010, 0.2733,  ..., 0.8556, 0.1585, 0.9253]],
       device='cuda:0')

Перемножим две тензора на GPu и вернём результат вычисления на CPU:

In [103]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [104]:
c

tensor([[0.7317, 0.3408, 0.8113,  ..., 0.0526, 0.4184, 0.5403],
        [0.5555, 0.0136, 0.4752,  ..., 0.0512, 0.0334, 0.0908],
        [0.1984, 0.2683, 0.0898,  ..., 0.0130, 0.0701, 0.3907],
        ...,
        [0.1373, 0.0130, 0.8432,  ..., 0.5088, 0.0102, 0.2102],
        [0.0071, 0.3411, 0.2942,  ..., 0.4084, 0.1954, 0.0792],
        [0.1853, 0.7131, 0.0204,  ..., 0.0052, 0.1005, 0.0019]])

In [105]:
a

tensor([[0.9823, 0.6496, 0.8451,  ..., 0.2325, 0.6633, 0.9007],
        [0.7278, 0.1242, 0.7470,  ..., 0.0891, 0.3112, 0.6948],
        [0.3101, 0.8315, 0.6887,  ..., 0.0778, 0.1213, 0.8384],
        ...,
        [0.2018, 0.0784, 0.9649,  ..., 0.5631, 0.2066, 0.3386],
        [0.0114, 0.5118, 0.5767,  ..., 0.5302, 0.2520, 0.0899],
        [0.2373, 0.9616, 0.0703,  ..., 0.0063, 0.2084, 0.1511]])

Тензоры, лежащие на CPU, и тензоры, лежащие на GPU, недоступны друг для друга:

In [106]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [107]:
a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Вот ещё немного про то, как можно работать с GPU:

In [108]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# проверяем, есть ли CUDA (то есть NVidia GPU)
if torch.cuda.is_available():
    # так можно получить имя устройства, которое связано с CUDA
    # (полезно в случае с несколькими видеокартами)
    device = torch.device('cuda')          # CUDA-device объект
    y = torch.ones_like(x, device=device)  # создаём тензор на GPU
    x = x.to(device)                       # тут можно просто ``.to("cuda")``
    z = x + y
    print(z)
    # с помощью``.to`` можно и изменить тип при перемещении
    print(z.to("cpu", torch.double))

tensor([[[1.6011, 1.7872, 1.7807, 1.3388, 1.4142],
         [1.4896, 1.6781, 1.6508, 1.9988, 1.7724],
         [1.9801, 1.7233, 1.6409, 1.2848, 1.6635],
         [1.8709, 1.6023, 1.5904, 1.9703, 1.9983],
         [1.5805, 1.0699, 1.8741, 1.1001, 1.9012]],

        [[1.1110, 1.4736, 1.0723, 1.1471, 1.3833],
         [1.8536, 1.6593, 1.3928, 1.8640, 1.9000],
         [1.2086, 1.5809, 1.6233, 1.7457, 1.4363],
         [1.0680, 1.2001, 1.6174, 1.4522, 1.0464],
         [1.7646, 1.4683, 1.9778, 1.3878, 1.1063]],

        [[1.3816, 1.0855, 1.6375, 1.2237, 1.9027],
         [1.8039, 1.3347, 1.8682, 1.1780, 1.2121],
         [1.6712, 1.7161, 1.8335, 1.6916, 1.2766],
         [1.2523, 1.2311, 1.5742, 1.8616, 1.2087],
         [1.1985, 1.1484, 1.8695, 1.8921, 1.9708]],

        [[1.0766, 1.6616, 1.1596, 1.8062, 1.2241],
         [1.7942, 1.2829, 1.4544, 1.0197, 1.2907],
         [1.2503, 1.0457, 1.3695, 1.6438, 1.0832],
         [1.2278, 1.2167, 1.2304, 1.6909, 1.2171],
         [1.9181, 1.1199,

<h3 style="text-align: center;">Autograd<b></b></h3>

Расшифровывается как Automatic Gradients (автоматическое взятие градиентов) - собственно, из названия понятно, что это модуль PyTorch, отвечающий за взятие производных.  

PyTorch (как и любой другой фреймворк глубокого обучения) может продифференцировать функцию практически любой сложности.

Импортируем нужный класс:

In [109]:
from torch.autograd import Variable

Идея заключается в слудеющем: "оборачиваем" тензор в класс Variable(), получаем тоже тензор, но он имеет способность вычислять себе градиенты.  

Если а - тензор, обернутый в Variable(), то при вызове a.backward() берутся градиенты по всем переменным, от которых зависит тензор a.

**Примечание:** Если вы используете версию `pytorch 0.4.0` или более новую, то ***`torch.Tensor` позволяет брать по нему градиенты, класс `Variable()` использовать не нужно.*** (`torch.Variable()` - deprecated).

Примеры:

In [110]:
x = torch.FloatTensor(3, 1).uniform_()
y = torch.FloatTensor(3, 1).uniform_()
w = torch.FloatTensor(3, 3).uniform_() 
b = torch.FloatTensor(3, 1).uniform_()

x = Variable(x, requires_grad=True)
y = Variable(x, requires_grad=False)
w = Variable(w, requires_grad=True)
b = Variable(b, requires_grad=True)

y_pred = (w @ x).add_(b)

loss = (y_pred - y).sum()

# берём градиенты
loss.backward()

In [111]:
x.grad

tensor([[2.4414],
        [1.8388],
        [1.8125]])

In [112]:
w.grad

tensor([[0.9294, 0.9569, 0.3485],
        [0.9294, 0.9569, 0.3485],
        [0.9294, 0.9569, 0.3485]])

In [113]:
b.grad

tensor([[1.],
        [1.],
        [1.]])

In [114]:
y.grad

**Обратите внимание** - градиенты лежат в поле `.grad` у тех тензоров (Variable'ов), по которым брали эти градиенты. Градиенты **не лежат** в той Variable, от которой они брались!

Получить тензор из `Variable()` можно с помощью поля `.data`:

In [115]:
x

tensor([[0.9294],
        [0.9569],
        [0.3485]], requires_grad=True)

In [116]:
x.data

tensor([[0.9294],
        [0.9569],
        [0.3485]])